config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'cocktails/spirit/:spirit', to: 'cocktails#specify', as: :specify
  resources :cocktails, only: [:index, :show, :new, :create]  do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: :destroy
  root to: 'cocktails#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @spirits = {gin: "https://images.unsplash.com/photo-1484132368430-ca5c967b425b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1932&q=80", vodka: "https://images.unsplash.com/photo-1516758288207-e9059e0b3b3f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3151&q=80", tequila: "https://images.unsplash.com/photo-1522128483605-23607c944cbb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1949&q=80", rum: "https://images.unsplash.com/photo-1505739817823-dcf70eb5a3f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80", whiskey: "https://images.unsplash.com/photo-1508253730651-e5ace80a7025?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80", vermouth: "https://images.unsplash.com/photo-1542848802-92864b33761c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1947&q=80", brandy: "https://images.unsplash.com/photo-1557515527-269958c615de?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80", all: "https://images.unsplash.com/photo-1482112048165-dd23f81c367d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"}

  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail.id)
    else
      render :new
    end
  end

  def specify
    if params[:background].nil?
      @background = "https://images.unsplash.com/photo-1482112048165-dd23f81c367d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"
      @cocktails = Cocktail.joins(:ingredients).where("ingredients.name ILIKE ? OR cocktails.name ILIKE ?", "%#{params[:search][:query]}%", "%#{params[:search][:query]}%").uniq
    else
      @background = params[:background]
      if params[:spirit] == "all"
        @cocktails = Cocktail.all
      else
        @cocktails = Cocktail.joins(:ingredients).where("ingredients.name ILIKE ?", "%#{params[:spirit]}%").uniq
      end
    end
  end


  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = @cocktail.id
    if @dose.save
      redirect_to cocktail_path(@cocktail.id)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(cocktail.id)
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<!-- BANNER -->
<%= render '/layouts/navbar' %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1509807995916-c332365e2d9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3071&q=80);">
  <div class="container">
    <h1>cocktailaculous</h1>
    <br>
    <br>
    <br>
    <br>
    <%= simple_form_for :search, url: specify_path("search"), method: :get do |f| %>
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Let's get you drunk..." />
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i> Search
        </button>
      </div>
    <% end %>
    <br>
    <p><em>Cocktail:</em> Came from a bartender who mixed her drinks with rooster tail feathers. One night a man came in and asked for "One of those cock-tails", and thus the phrase was born. </p>
  </div>
</div>

<div class="background">
  <div class="container py-5">
    <% @spirits.each do |spirit, img_url| %>
      <%= link_to specify_path(spirit, background: img_url) do %>
        <div class="card-category my-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= img_url %>)">
          <%= spirit.capitalize %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= render '/layouts/navbar' %>
<div class ="background-new" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1949&q=80);">
  <div class="container w-50 pt-5 new-form">

    <h1>New Cocktail</h1>
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit "Add Cocktail", class: "btn btn-dark" %>
    <% end %>

  </div>

</div>

app/views/cocktails/show.html.erb
<%= render '/layouts/navbar' %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @cocktail.photo %>);">
  <div class="container">
    <br>
    <br>
    <h1><%= @cocktail.name %></h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="description col-6 pt-3">
      <h2>Description</h2>
      <br>
      <p><%= @cocktail.description %></p>
    </div>
    <div class="ingredients col-6 py-3">
      <h2>Ingredients</h2>
      <br>
      <% @cocktail.doses.each do |dose| %>
        <p><%= dose.description %> <%= dose.ingredient.name %> <%= link_to dose_path(dose.id), method: :delete do %> <i class="fas fa-trash ml-3"></i> <% end %></p>
      <% end %>
      <%= link_to "Add ingredient", new_cocktail_dose_path(@cocktail.id), class: "btn btn-outline-light" %>
    </div>
  </div>
</div>

app/views/cocktails/specify.html.erb
<%= render '/layouts/navbar' %>
<div class ="background-new" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @background %>);">
  <div class="container py-5">
    <div class="cards mt-5">
      <% @cocktails.each do |cocktail| %>
        <%= link_to cocktail_path(cocktail.id) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= cl_image_path cocktail.photo %>)">
            <%= cocktail.name %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<%= render '/layouts/navbar' %>
<div class ="background-new" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1558201202-e65298e2e869?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80);">
  <div class="container w-50 pt-5 new-form">

    <h1>New Ingredient</h1>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient %>
      <%= f.input :description, label: "Specify amount (parts, cl, dash, etc.)" %>
      <%= f.submit "Add Ingredient", class: "btn btn-dark" %>
    <% end %>

  </div>

</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to cocktails_path, class: "navbar-brand icon" do %>
    <i class="fas fa-cocktail"></i>
  <% end %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Add Cocktail", new_cocktail_path , class: "btn btn-outline-light" %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>cocktailaculous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>